### PR TITLE
Use explicit filename when downloading Windows go package

### LINKED ISSUE #241: Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format. - Windows Runner
**Description:**
Setup Windows 10 Runner without go installed already.
After setting up I have a step on my workflow: actions/setup-go@v3
Placed the full error at the bottom.

**Action version:**
actions/setup-go@v3

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
go 1.18

**Repro steps:**  
Setup a self hosted runner on a fresh Windows 10 install.
Specify a step in a go project to use acitons/setup-go@v3 on the self hosted windows runner.
You should get the error specified below.

**Expected behavior:**
During the extract process go should be extracted.

**Actual behavior:**
Receive the following error.
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.

```
Run actions/setup-go@v3
Setup go version spec 1.18
Attempting to download 1.18...
matching 1.18...
Acquiring 1.18.3 from https://github.com/actions/go-versions/releases/download/1.18.3-2426432064/go-1.18.3-win32-x64.zip
Extracting Go...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner\_work\_temp\69939204-4b8f-4ec8-b18f-b0dc2509d44c' -DestinationPath 'C:\Users\User\actions-runner\_work\_temp\43363100-5525-4011-867d-ef3863a56e8a' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\User\actions-runner\_work\_temp\69939204-4b8f-4ec8-b18f-b0dc2509d44c', 'C:\Users\User\actions-runner\_work\_temp\43363100-5525-4011-867d-ef3863a56e8a', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
Falling back to download directly from Go
Install from dist
Acquiring go1.18.3 from https://storage.googleapis.com/golang/go1.18.3.windows-amd64.zip
Extracting Go...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; if ((Get-Command -Name Expand-Archive -Module Microsoft.PowerShell.Archive -ErrorAction Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner\_work\_temp\8352c1a6-99ab-4b64-9920-1[15](https://github.com/redanthrax/rmmagent/runs/7097201014?check_suite_focus=true#step:3:16)dfe35207b' -DestinationPath 'C:\Users\User\actions-runner\_work\_temp\7bd5e377-42b4-4930-8126-a6342480422f' -Force } else {[System.IO.Compression.ZipFile]::ExtractToDirectory('C:\Users\User\actions-runner\_work\_temp\8352c1a6-99ab-4b64-9920-115dfe35207b', 'C:\Users\User\actions-runner\_work\_temp\7bd5e377-42b4-4930-8126-a6342480422f', $true) }"
Expand-Archive :  is not a supported archive file format. .zip is the only supported archive file format.
At line:1 char:210
+ ...  Ignore)) { Expand-Archive -LiteralPath 'C:\Users\User\actions-runner ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:String) [Expand-Archive], IOException
    + FullyQualifiedErrorId : NotSupportedArchiveFileExtension,Expand-Archive
Error: Failed to download version 1.[18](https://github.com/redanthrax/rmmagent/runs/7097201014?check_suite_focus=true#step:3:19): Error: The process 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' failed with exit code 1
```

### PR DESCRIPTION
**Pull request by jromero**
**Description:**
Use explicit filename when downloading Windows go package.

Using the explicit filename for Windows is necessary to satisfy `Expand-Archive`'s requirement on `.zip` extension.

The solution can be seen working [here](https://github.com/buildpacks/pack/runs/7570679322?check_suite_focus=true) ([screenshot](https://user-images.githubusercontent.com/475559/181657378-24702fd4-d567-4c36-83b3-e1e6e59b0899.png)).

---

Credit goes to @redanthrax for finding the root cause. 

This PR differs from https://github.com/actions/setup-go/pull/242 in the following ways:

1. When available, uses `RUNNER_TEMP` env var similar to [tool-cache](https://github.com/actions/toolkit/blob/01e1ff7bc04e1c57c980a0d1530478a5b60cf812/packages/tool-cache/src/tool-cache.ts#L755-L759).
2. Added tests for the implemented scenario.
3. It **DOES NOT** update `tool-cache` library (to minimize changes).

---

**Related issue:**

Fixes #241

**Check list:**
- [ ] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

File: src/installer.ts [hunk 1]
```diff
@@ -132,7 +132,13 @@ async function installGoVersion(
   auth: string | undefined
 ): Promise<string> {
   core.info(`Acquiring ${info.resolvedVersion} from ${info.downloadUrl}`);
-  const downloadPath = await tc.downloadTool(info.downloadUrl, undefined, auth);
+
+  // Windows requires that we keep the extension (.zip) for extraction
+  const isWindows = os.platform() === 'win32';
+  const tempDir = process.env.RUNNER_TEMP || '.';
```
Comment (dmitry-shibanov) [inline src/installer.ts:138]: I am not sure that we need to add tempDir. As I know `downloadTool` command should handle it.

Comment (jromero) [reply src/installer.ts:138]: IIRC, it only does it if dest is undefined. In the Windows case we provide a file name which ends up relative. This variable is only used in the Windows case, on others we let downloadTool handle all of it.

Comment (dmitry-shibanov) [reply src/installer.ts:138]: I've checked it. You're right. In this case I think it should work. Thank you.

**Review by dmitry-shibanov — APPROVED** [review]

**Review by marko-zivic-93 — APPROVED** [review]

**Review by panticmilos — APPROVED** [review]

**Comment by jromero** [comment]
@dmitry-shibanov / @marko-zivic-93 Any insight as to when this may be merged and/or released?

**Comment by milas** [comment]
I just saw this after updating a job to use 1.19 on a shared runner - any chance we can get a v3.2.2 released?

**Comment by panticmilos** [comment]
Hi @milas, we will get release for this today or tomorrow :)

**Comment by panticmilos** [comment]
Hi guys, just to update you, the release will be at the start of the next week intead. We were waiting for one more feature to include in the release.

**Comment by panticmilos** [comment]
@jromero, @milas new release is out :)
